name: Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - 'jitpack.yml'
      - '.run/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - 'jitpack.yml'
      - '.run/**'

jobs:
  build:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:

      # Testing the plugin source requires checking out into `buildSrc`.
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Get latest Corretto URL
        id: get-latest-corretto-url
        run: >-
          echo "::set-output name=URL::$(curl -LIs -o /dev/null -w
          %{url_effective}
          https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz)"

      - uses: actions/cache@v3
        id: corretto-cache
        name: Restore Corretto
        with:
          path: ./amazon-corretto-17-x64-linux-jdk.tar.gz
          key: >-
            ${{ runner.os }}-corretto-${{
            steps.get-latest-corretto-url.outputs.URL }}

      - name: Download AWS Corretto
        if: steps.corretto-cache.outputs.cache-hit != 'true'
        run: >-
          wget
          https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: '17'
          architecture: x64
          jdkFile: ./amazon-corretto-17-x64-linux-jdk.tar.gz

      - name: 🔢 Configure build
        shell: bash
        env:
          JAVA_KEYSTORE_DEBUG: ${{ secrets.JAVA_KEYSTORE_DEBUG }}
          JAVA_KEYSTORE_UPLOAD: ${{ secrets.JAVA_KEYSTORE_UPLOAD }}
          JAVA_KEYSTORE_PROPERTIES: ${{ secrets.JAVA_KEYSTORE_PROPERTIES }}
        run: |
          chmod +x ./gradlew
          mkdir ~/.android
          mkdir $GITHUB_WORKSPACE/distribution
          echo $JAVA_KEYSTORE_DEBUG > ~/.android/debug.keystore
          echo $JAVA_KEYSTORE_UPLOAD > ~/.android/upload.keystore
          echo $JAVA_KEYSTORE_PROPERTIES > $GITHUB_WORKSPACE/keystore.properties

      - name: Build with Gradle
        run: |
          ./gradlew :build
          cd ./build/libs
          ls -la | grep jar

      - name: 📦 Retain Artifact (JAR)
        id: retain-plugin-jar
        uses: actions/upload-artifact@v3
        with:
          name: buildSrc
          path: ./build/libs/*.jar
          retention-days: 14
